#!/usr/bin/env python3
"""Convert a raw binary into a TMPx .byte include with a label and a length
constant, so a tool can embed another assembled blob (pack_tool.asm embeds
pack_stub.bin this way).

Usage: bin2inc.py in.bin out.inc LABEL
"""
from __future__ import annotations

import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    data = Path(sys.argv[1]).read_bytes()
    label = sys.argv[3]
    lines = [f"; generated by tools/bin2inc.py from {Path(sys.argv[1]).name}"
             f" -- do not edit", label]
    for i in range(0, len(data), 16):
        chunk = ",".join(f"${b:02x}" for b in data[i:i + 16])
        lines.append(f" .byte {chunk}")
    lines.append(f"{label.upper()}_LEN = {len(data)}")
    lines.append("")
    Path(sys.argv[2]).write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
